In [2]:
from sklearn.cluster import DBSCAN
from sklearn.preprocessing import StandardScaler
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
#Read the file
df = pd.read_csv("EastWestAirlines.csv")

In [4]:
df.head()

ID#  Balance  Qual_miles  cc1_miles  cc2_miles  cc3_miles  Bonus_miles  \
0    1    28143           0          1          1          1          174   
1    2    19244           0          1          1          1          215   
2    3    41354           0          1          1          1         4123   
3    4    14776           0          1          1          1          500   
4    5    97752           0          4          1          1        43300   

   Bonus_trans  Flight_miles_12mo  Flight_trans_12  Days_since_enroll  Award?  
0            1                  0                0               7000       0  
1            2                  0                0               6968       0  
2            4                  0                0               7034       0  
3            1                  0                0               6952       0  
4           26               2077                4               6935       1

In [7]:
data=df.drop(columns={"ID#","Award?"})

In [8]:
data

Balance  Qual_miles  cc1_miles  cc2_miles  cc3_miles  Bonus_miles  \
0       28143           0          1          1          1          174   
1       19244           0          1          1          1          215   
2       41354           0          1          1          1         4123   
3       14776           0          1          1          1          500   
4       97752           0          4          1          1        43300   
...       ...         ...        ...        ...        ...          ...   
3994    18476           0          1          1          1         8525   
3995    64385           0          1          1          1          981   
3996    73597           0          3          1          1        25447   
3997    54899           0          1          1          1          500   
3998     3016           0          1          1          1            0   

      Bonus_trans  Flight_miles_12mo  Flight_trans_12  Days_since_enroll  
0               1                  0                0               7000  
1               2                  0                0               6968  
2               4                  0                0               7034  
3               1                  0                0               6952  
4              26               2077                4               6935  
...           ...                ...              ...                ...  
3994            4                200                1               1403  
3995            5                  0                0               1395  
3996            8                  0                0               1402  
3997            1                500                1               1401  
3998            0                  0                0               1398  

[3999 rows x 10 columns]

In [9]:
array=data.values

In [10]:
array

array([[28143,     0,     1, ...,     0,     0,  7000],
       [19244,     0,     1, ...,     0,     0,  6968],
       [41354,     0,     1, ...,     0,     0,  7034],
       ...,
       [73597,     0,     3, ...,     0,     0,  1402],
       [54899,     0,     1, ...,   500,     1,  1401],
       [ 3016,     0,     1, ...,     0,     0,  1398]], dtype=int64)

In [11]:
#Standardizing the data using Standardscaler func
stscaler = StandardScaler().fit(array)
X = stscaler.transform(array)

In [12]:
X

array([[-4.51140783e-01, -1.86298687e-01, -7.69578406e-01, ...,
        -3.28603258e-01, -3.62167870e-01,  1.39545434e+00],
       [-5.39456874e-01, -1.86298687e-01, -7.69578406e-01, ...,
        -3.28603258e-01, -3.62167870e-01,  1.37995704e+00],
       [-3.20031232e-01, -1.86298687e-01, -7.69578406e-01, ...,
        -3.28603258e-01, -3.62167870e-01,  1.41192021e+00],
       ...,
       [-4.29480975e-05, -1.86298687e-01,  6.83121167e-01, ...,
        -3.28603258e-01, -3.62167870e-01, -1.31560393e+00],
       [-1.85606976e-01, -1.86298687e-01, -7.69578406e-01, ...,
         2.85309024e-02, -9.85033311e-02, -1.31608822e+00],
       [-7.00507951e-01, -1.86298687e-01, -7.69578406e-01, ...,
        -3.28603258e-01, -3.62167870e-01, -1.31754109e+00]])

In [13]:
#Assigning the eps value and min points and creating the model and forming clusters
dbscan = DBSCAN(eps=5, min_samples=11)
dbscan.fit(X)

DBSCAN(eps=5, min_samples=11)

In [14]:
dbscan.labels_

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [17]:
cl=pd.Series(dbscan.labels_)

In [18]:
cl

0       0
1       0
2       0
3       0
4       0
       ..
3994    0
3995    0
3996    0
3997    0
3998    0
Length: 3999, dtype: int64

In [19]:
df['cluster']=cl

In [20]:
df

ID#  Balance  Qual_miles  cc1_miles  cc2_miles  cc3_miles  Bonus_miles  \
0        1    28143           0          1          1          1          174   
1        2    19244           0          1          1          1          215   
2        3    41354           0          1          1          1         4123   
3        4    14776           0          1          1          1          500   
4        5    97752           0          4          1          1        43300   
...    ...      ...         ...        ...        ...        ...          ...   
3994  4017    18476           0          1          1          1         8525   
3995  4018    64385           0          1          1          1          981   
3996  4019    73597           0          3          1          1        25447   
3997  4020    54899           0          1          1          1          500   
3998  4021     3016           0          1          1          1            0   

      Bonus_trans  Flight_miles_12mo  Flight_trans_12  Days_since_enroll  \
0               1                  0                0               7000   
1               2                  0                0               6968   
2               4                  0                0               7034   
3               1                  0                0               6952   
4              26               2077                4               6935   
...           ...                ...              ...                ...   
3994            4                200                1               1403   
3995            5                  0                0               1395   
3996            8                  0                0               1402   
3997            1                500                1               1401   
3998            0                  0                0               1398   

      Award?  cluster  
0          0        0  
1          0        0  
2          0        0  
3          0        0  
4          1        0  
...      ...      ...  
3994       1        0  
3995       1        0  
3996       1        0  
3997       0        0  
3998       0        0  

[3999 rows x 13 columns]

In [21]:
df.iloc[:,1:].groupby(df.cluster).mean()

Balance  Qual_miles  cc1_miles  cc2_miles  cc3_miles  \
cluster                                                               
-1       231312.769231  476.153846   3.038462        1.0   2.884615   
 0        72609.639695  143.240204   2.063104        1.0   1.000000   
 1        52231.400000   66.666667   1.000000        3.0   1.000000   
 2        77793.642857    0.000000   1.214286        2.0   1.000000   

          Bonus_miles  Bonus_trans  Flight_miles_12mo  Flight_trans_12  \
cluster                                                                  
-1       82085.538462    34.076923        4379.000000        11.192308   
 0       16742.074555    11.388295         432.787786         1.299491   
 1       20410.466667    18.933333         692.666667         3.200000   
 2       11625.214286    16.785714         523.678571         1.678571   

         Days_since_enroll    Award?  cluster  
cluster                                        
-1             4395.115385  0.653846       -1  
 0             4118.366921  0.368193        0  
 1             4075.533333  0.400000        1  
 2             3911.821429  0.392857        2